Repository bitia-ru/gekkon-m-frontend, pull requests merged in 2020-12, with the labels that each got.

#172 GFM-171: Разбить фильтр 6В-7А+ на два: 6В-6С+ и 6С-7А+
  src/v1/Constants/Categories.js
  src/v2/components/FilterBlock/FilterBlock.js
Labels: enhancement

#174 GFM-173: Добавить фильтр "Период -> Две недели" и "Год" заменить на "2 месяца"
  src/v1/Constants/PeriodFilters.js
  src/v2/utils/reloadRoutes.js
Labels: enhancement

#152 GFM-150: На iOS, в полях ввода номера и заголовка трассы текст скрывается за пределами полей.
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: bug

#180 GFM-179: Sort spots by activity (stage 2)
  src/v2/components/MainPageContent/MainPageContent.js
Labels: release

#181 Release/0.11.0
  src/v2/components/MainPageContent/MainPageContent.js
Labels: release
