Repository bitia-ru/gekkon-m-frontend, pull requests merged in 2020-11, with the labels that each got.

#113 GFM-112: Переделать логику переходов по history при открытии окон просмотра/редактирования трассы
  src/v1/components/CloseButton/CloseButton.js
  src/v2/components/RoutesEditModal/RoutesEditModal.js
  src/v2/components/RoutesShowModal/RoutesShowModal.js
  src/v2/screens/SpotsShow.jsx
Labels: enhancement

#137 GFM-136: Сохранять позицию скролла для окна со списком трасс после просмотра трассы
  src/v2/components/RoutesEditModal/RoutesEditModal.js
  src/v2/components/RoutesShowModal/RoutesShowModal.js
  src/v2/screens/SpotsShow.jsx
Labels: enhancement

#149 GFM-148: Проблема совместимости мобильных браузеров с методом scrollIntoView() - не сохраняется позиция скролла
  src/v2/components/RouteCardScheme/RouteCardScheme.js
  src/v2/components/RouteCardView/RouteCardView.js
  src/v2/contexts/MainScreenContext.js
  src/v2/layouts/MainScreen/MainScreen.jsx
  src/v2/utils/scrollIntoView.js
Labels: bug

#165 GFM-164: Не работает крестик в окне просмотра трассы
  src/v2/modules/modalable/index.jsx
Labels: bug

#166 GFM-164: Fix close show route window
  src/v2/modules/modalable/index.jsx
Labels: hotfix

#161 GFM-153: После сохранения трассы кроп слетает
  src/v2/components/RoutePhotoCropper/RoutePhotoCropper.js
Labels: bug

#163 GFM-154: После загрузки фотографии трассы она отображается не на весь экран
  src/v2/components/RoutePhotoCropper/RoutePhotoCropper.js
Labels: bug

#158 GFM-155: Неверно отображается текущая дата накрутки/скрутки
  src/v2/components/DatePickerSelector/DatePickerSelector.jsx
  src/v2/components/FilterBlock/FilterBlock.js
Labels: bug

#162 GFM-147: Брать дату пролаза при добавлении пролаза из даты в фильтрах на схеме зала
  src/v2/forms/RouteAscents/RouteAscents.jsx
Labels: enhancement

#170 Release/0.9.3
  src/v2/components/MainPageContent/MainPageContent.js
Labels: hotfix
