Repository bitia-ru/gekkon-m-frontend, pull requests merged in 2021-02, with the labels that each got.

#187 GFM-186: Загрузка фотографии по клику на плюс (когда фотки нет)
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: enhancement

#185 GFM-184: При входе через Vk игнорируется чек-бокс "запомнить меня"
  src/v2/forms/LogInForm/LogInForm.js
  src/v2/utils/vk.js
Labels: bug

#190 GFM-188: Fix ErrorBoundary and enhance its page
  src/ErrorBoundary.jsx
  src/v1/index.js
  src/v1/reducers.js
  src/v1/store.js
  src/v2/redux/initializedAt/reducer.js
  src/v2/utils/ExceptionTestComponent.jsx
Labels: enhancement

#195 Release/0.12.1
  webpack.config.js
Labels: release

#197 GFM-196: Автоматическое проставление категории по цвету маркировки
  src/v2/components/RouteDataEditableTable/RouteDataEditableTable.js
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: feature

#199 GFM-198: Убрать из бутербродного меню кнопку "Режим накрутчика"
  src/v1/Constants/User.js
  src/v1/components/MainMenu/MainMenu.js
  src/v2/components/MainMenu/MainMenu.js
Labels: enhancement
