Repository bitia-ru/gekkon-m-frontend, pull requests merged in 2021-03, with the labels that each got.

#201 GFM-200: Выделять стрелочки разметки, которые отвечают за кадрирование
  src/v1/Constants/Marker.js
  src/v1/components/Marker/Marker.js
  src/v1/components/Marker/images/hold-mark.png
  src/v1/components/Marker/images/regular.svg
  src/v1/components/Marker/images/start.svg
  src/v1/components/Marker/utils.js
  src/v2/components/RouteEditor/RouteEditor.js
  src/v2/components/RouteView/RouteView.js
Labels: enhancement

#204 GFM-203: Fix nginx.conf after index-[hash].js -> index-mob.js renaming
  docker/configs/nginx.conf
Labels: bug

#205 Release/0.13.1
  docker/configs/nginx.conf
Labels: hotfix

#207 GFM-206: Изменить сообщение о невалидном логине
  src/v1/components/Profile/Profile.js
  src/v2/forms/Profile/Profile.js
Labels: enhancement

#210 GFM-209: Add autocomplete off for Profile window
  src/v1/components/FormField/FormField.js
  src/v2/forms/Profile/Profile.js
Labels: bug

#212 GFM-211: После логина не закрывается модальное окно
  src/v2/forms/LogInForm/LogInForm.js
  src/v2/forms/SignUpForm/SignUpForm.js
Labels: hotfix
